'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5472
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5472.
'
Namespace AEPM_Services
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IServices", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(CrossPart))>  _
    Partial Public Class Services
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetMasterOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AddMasterOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.AEPM_APICmd.My.MySettings.Default.ConsoleApplication1_corp_nmhg_global_enmdevex_Services
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetMasterCompleted As GetMasterCompletedEventHandler
        
        '''<remarks/>
        Public Event AddMasterCompleted As AddMasterCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://tempuri.org/IServices/GetMaster", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/")>  _
        Public Function GetMaster(ByVal PartNumber As String) As GetMasterResult
            Dim results() As Object = Me.Invoke("GetMaster", New Object() {PartNumber})
            Return CType(results(0),GetMasterResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetMasterAsync(ByVal PartNumber As String)
            Me.GetMasterAsync(PartNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetMasterAsync(ByVal PartNumber As String, ByVal userState As Object)
            If (Me.GetMasterOperationCompleted Is Nothing) Then
                Me.GetMasterOperationCompleted = AddressOf Me.OnGetMasterOperationCompleted
            End If
            Me.InvokeAsync("GetMaster", New Object() {PartNumber}, Me.GetMasterOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetMasterOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetMasterCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetMasterCompleted(Me, New GetMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://tempuri.org/IServices/AddMaster", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/")>  _
        Public Function AddMaster(ByVal UserID As String, ByVal CrossPartList() As CrossPart, ByVal Branded As Boolean, ByVal Commodity_Code As String, ByVal Level As Short, ByVal Status As String, ByVal Returnable As Boolean, ByVal Tariff_Code As String, ByVal AMSC As String, ByVal Technical_Qty As Integer, ByVal Service_Life As Integer, ByVal Package_Code As String, ByVal Information As String) As AddMasterResult
            Dim results() As Object = Me.Invoke("AddMaster", New Object() {UserID, CrossPartList, Branded, Commodity_Code, Level, Status, Returnable, Tariff_Code, AMSC, Technical_Qty, Service_Life, Package_Code, Information})
            Return CType(results(0),AddMasterResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AddMasterAsync(ByVal UserID As String, ByVal CrossPartList() As CrossPart, ByVal Branded As Boolean, ByVal Commodity_Code As String, ByVal Level As Short, ByVal Status As String, ByVal Returnable As Boolean, ByVal Tariff_Code As String, ByVal AMSC As String, ByVal Technical_Qty As Integer, ByVal Service_Life As Integer, ByVal Package_Code As String, ByVal Information As String)
            Me.AddMasterAsync(UserID, CrossPartList, Branded, Commodity_Code, Level, Status, Returnable, Tariff_Code, AMSC, Technical_Qty, Service_Life, Package_Code, Information, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddMasterAsync(ByVal UserID As String, ByVal CrossPartList() As CrossPart, ByVal Branded As Boolean, ByVal Commodity_Code As String, ByVal Level As Short, ByVal Status As String, ByVal Returnable As Boolean, ByVal Tariff_Code As String, ByVal AMSC As String, ByVal Technical_Qty As Integer, ByVal Service_Life As Integer, ByVal Package_Code As String, ByVal Information As String, ByVal userState As Object)
            If (Me.AddMasterOperationCompleted Is Nothing) Then
                Me.AddMasterOperationCompleted = AddressOf Me.OnAddMasterOperationCompleted
            End If
            Me.InvokeAsync("AddMaster", New Object() {UserID, CrossPartList, Branded, Commodity_Code, Level, Status, Returnable, Tariff_Code, AMSC, Technical_Qty, Service_Life, Package_Code, Information}, Me.AddMasterOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddMasterOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddMasterCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddMasterCompleted(Me, New AddMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://tempuri.org/encoded")>  _
    Partial Public Class GetMasterResult
        
        Private crossPartListField() As CrossPart
        
        Private brandedField As Boolean
        
        Private commodity_CodeField As String
        
        Private levelField As Short
        
        Private statusField As String
        
        Private returnableField As Boolean
        
        Private tariff_CodeField As String
        
        Private aMSCField As String
        
        Private technical_QtyField As Integer
        
        Private service_LifeField As Integer
        
        Private package_CodeField As String
        
        Private informationField As String
        
        Private userIDField As String
        
        Private dateCreatedField As Date
        
        Private successField As Boolean
        
        Private errorField As String
        
        '''<remarks/>
        Public Property CrossPartList() As CrossPart()
            Get
                Return Me.crossPartListField
            End Get
            Set
                Me.crossPartListField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Branded() As Boolean
            Get
                Return Me.brandedField
            End Get
            Set
                Me.brandedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Commodity_Code() As String
            Get
                Return Me.commodity_CodeField
            End Get
            Set
                Me.commodity_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Level() As Short
            Get
                Return Me.levelField
            End Get
            Set
                Me.levelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Returnable() As Boolean
            Get
                Return Me.returnableField
            End Get
            Set
                Me.returnableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tariff_Code() As String
            Get
                Return Me.tariff_CodeField
            End Get
            Set
                Me.tariff_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AMSC() As String
            Get
                Return Me.aMSCField
            End Get
            Set
                Me.aMSCField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Technical_Qty() As Integer
            Get
                Return Me.technical_QtyField
            End Get
            Set
                Me.technical_QtyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Service_Life() As Integer
            Get
                Return Me.service_LifeField
            End Get
            Set
                Me.service_LifeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Package_Code() As String
            Get
                Return Me.package_CodeField
            End Get
            Set
                Me.package_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Information() As String
            Get
                Return Me.informationField
            End Get
            Set
                Me.informationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserID() As String
            Get
                Return Me.userIDField
            End Get
            Set
                Me.userIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DateCreated() As Date
            Get
                Return Me.dateCreatedField
            End Get
            Set
                Me.dateCreatedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Success() As Boolean
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [Error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://tempuri.org/encoded")>  _
    Partial Public Class CrossPart
        
        Private brandField As String
        
        Private partNumberField As String
        
        '''<remarks/>
        Public Property Brand() As String
            Get
                Return Me.brandField
            End Get
            Set
                Me.brandField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PartNumber() As String
            Get
                Return Me.partNumberField
            End Get
            Set
                Me.partNumberField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://tempuri.org/encoded")>  _
    Partial Public Class AddMasterResult
        
        Private successField As Boolean
        
        Private errorField As String
        
        '''<remarks/>
        Public Property Success() As Boolean
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [Error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub GetMasterCompletedEventHandler(ByVal sender As Object, ByVal e As GetMasterCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetMasterCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetMasterResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetMasterResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub AddMasterCompletedEventHandler(ByVal sender As Object, ByVal e As AddMasterCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AddMasterCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AddMasterResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AddMasterResult)
            End Get
        End Property
    End Class
End Namespace
